## **Setup**

In [1]:
import os, sys

# Repository information
REPO_NAME = "RecSys-Challenge-2025"
REPO_URL  = f"github.com/Lv1g1/{REPO_NAME}.git"

# Detect environment
IS_COLAB = 'content' in os.getcwd()
IS_KAGGLE = 'kaggle' in os.getcwd()
IS_LOCAL = not (IS_COLAB or IS_KAGGLE)

WORKING_DIR = os.getcwd()

if IS_COLAB:
    WORKING_DIR = "/content"

    # Mount Google Drive
    from google.colab import drive
    drive.mount('/content/drive', force_remount=False)

    # Get GitHub token via input
    def get_token():
        from getpass import getpass
        return getpass("GitHub Token: ")

elif IS_KAGGLE:
    WORKING_DIR = "/kaggle/working"

    # Get GitHub token from Kaggle secrets
    def get_token():
        from kaggle_secrets import UserSecretsClient
        return UserSecretsClient().get_secret("Token")

# If local environment assume inside the repo
LOCAL_REPO_PATH = "/home/luigi/RecSys" if IS_LOCAL else os.path.join(WORKING_DIR, REPO_NAME)

# Clone the repository if it doesn't exist
if not os.path.exists(LOCAL_REPO_PATH):
    os.chdir(WORKING_DIR)
    token = get_token()

    !git clone https://{token}@{REPO_URL}
else:
    print("Repo already exists — pulling latest changes")
    os.chdir(LOCAL_REPO_PATH)
    !git pull
    os.chdir(WORKING_DIR)

# Add to Python PATH
if LOCAL_REPO_PATH not in sys.path:
    sys.path.append(LOCAL_REPO_PATH)

if IS_COLAB:
    !pip install optuna

Repo already exists — pulling latest changes
fatal: unable to access 'https://github.com/Lv1g1/RecSys-Challenge-2025.git/': Could not resolve host: github.com

In [2]:
if IS_COLAB or False:  # Set to True if you want to recompile Cython files
    os.chdir(LOCAL_REPO_PATH)
    !python run_compile_all_cython.py
    os.chdir(WORKING_DIR)

In [ ]:
import pandas as pd
import os
import optuna
from xgboost import XGBRanker
from sklearn.metrics import roc_auc_score
import gc

from Challenge.paths import load_xgboost_cv_folds, XGBOOST_DATAFRAMES
from Challenge.hyper_tuning import ModelOptimizer
from Challenge.utils import evaluate_recommender
from Challenge.XGBoostReranker import XGBoostRerankerRecommender

Running on local — storage at: /home/luigi/RecSys

/home/luigi/RecSys/Challenge/hyper_tuning.py:75: ExperimentalWarning: WilcoxonPruner is experimental (supported from v3.6.0). The interface can change in the future.
  def create_study(self, study_name, direction="maximize", load_if_exists=True, pruner=optuna.pruners.WilcoxonPruner()):
/home/luigi/RecSys/Challenge/hyper_tuning.py:107: ExperimentalWarning: WilcoxonPruner is experimental (supported from v3.6.0). The interface can change in the future.
  def create_and_optimize_study(self, study_name, objective_function, n_trials=50, direction="maximize", load_if_exists=True, pruner=optuna.pruners.WilcoxonPruner()):

## **Load Data**

In [4]:
_, URM_outer, _ = load_xgboost_cv_folds()
del _

In [5]:
file_path = os.path.join(XGBOOST_DATAFRAMES, "training_data.parquet")

X_train = pd.read_parquet(
    file_path,
    engine='fastparquet'
)

print(f"Loaded successfully from: {file_path}")
X_train

Loaded successfully from: /home/luigi/RecSys/xg_boost_data/dataframes/training_data.parquet

          UserID  ItemID  ...  User_Profile_Len  Item_Global_Popularity
0              0    5609  ...                58                    2319
1              0    1940  ...                60                    5214
2              0    3258  ...                60                     670
3              0    1504  ...                60                     111
4              0    3754  ...                60                     599
...          ...     ...  ...               ...                     ...
18951167   27094    5710  ...               203                    1149
18951168   27094     922  ...               203                      23
18951169   27094    2879  ...               203                      19
18951170   27094    6584  ...               203                    3531
18951171   27094    1554  ...               211                    3316

[18951172 rows x 83 columns]

In [6]:
if not X_train['UserID'].is_monotonic_increasing:
    print("⚠️ Data is NOT sorted by UserID.")
    print("Sorting and overwriting file for future efficiency...")
    
    # Sort and reset index (critical for contiguous memory in ML)
    X_train = X_train.sort_values(by='UserID').reset_index(drop=True)
    
    # Overwrite the file on disk
    X_train.to_parquet(
        path=file_path,
        engine='fastparquet',
        compression='zstd',
        index=False
    )
    
    print(f"✅ Data sorted and saved to {file_path}")

In [7]:
assert X_train['UserID'].is_monotonic_increasing, "UserID column is not sorted in increasing order!"

# Group Calculation
groups = X_train.groupby("UserID").size().values

# Target and Feature Matrix Definition
y_train = X_train["Label"]

# Drop the identifiers (UserID, ItemID) and the target (Label), keeping only the features
X_train = X_train.drop(columns=["Label", "UserID", "ItemID"], errors='ignore') 

assert groups.sum() == X_train.shape[0], "Group sum does not match total data size!"

In [8]:
file_path = os.path.join(XGBOOST_DATAFRAMES, "validation_data.parquet")

X_val = pd.read_parquet(
    file_path,
    engine='fastparquet'
)

print(f"Loaded successfully from: {file_path}")
X_val

Loaded successfully from: /home/luigi/RecSys/xg_boost_data/dataframes/validation_data.parquet

         UserID  ItemID  ...  User_Profile_Len  Item_Global_Popularity
0             0    6411  ...                80                     874
1             0    2168  ...                80                     841
2             0    6098  ...                80                     878
3             0    3049  ...                80                    1368
4             0    2399  ...                80                    4721
...         ...     ...  ...               ...                     ...
3756433   27094    4180  ...               250                    3922
3756434   27094    3236  ...               250                    6339
3756435   27094    4615  ...               250                      47
3756436   27094    6584  ...               250                    4403
3756437   27094     426  ...               250                      30

[3756438 rows x 83 columns]

In [ ]:
recommender = XGBoostRerankerRecommender(
    XGB_model=None,
    df=X_val
)

## **Optimize XG Boost hypeparameters**

In [9]:
optimizer = ModelOptimizer("XG_Boost_v1")

In [10]:
STUDY_NAME = XGBoostRerankerRecommender.RECOMMENDER_NAME + "_v1_1"

In [ ]:
def objective_function(optuna_trial: optuna.trial.Trial) -> float:
    params = {
        'learning_rate': optuna_trial.suggest_float('learning_rate', 1e-3, 0.3, log=True),
        'n_estimators': optuna_trial.suggest_int('n_estimators', 20, 1000),
        'max_depth': optuna_trial.suggest_int('max_depth', 3, 10),
        'reg_alpha': optuna_trial.suggest_float('reg_alpha', 1e-3, 10.0, log=True),
        'reg_lambda': optuna_trial.suggest_float('reg_lambda', 1e-3, 10.0, log=True),
        'colsample_bytree': optuna_trial.suggest_float('colsample_bytree', 0.4, 1.0),
        'subsample': optuna_trial.suggest_float('subsample', 0.6, 1.0),
        
        # You can tune the objective too, but pairwise is usually standard for ranking
        'objective': optuna_trial.suggest_categorical('objective', ['rank:pairwise', 'rank:ndcg']),
        'grow_policy': 'depthwise' # Keep this fixed or tune ['depthwise', 'lossguide']
    }

    # Instantiate XGB model with current hyperparameters
    XGB_model = XGBRanker(
        objective=params['objective'],
        n_estimators=params['n_estimators'],
        learning_rate=params['learning_rate'],
        max_depth=params['max_depth'],
        reg_alpha=params['reg_alpha'],
        reg_lambda=params['reg_lambda'],
        colsample_bytree=params['colsample_bytree'],
        subsample=params['subsample'],
        grow_policy=params['grow_policy'],
        n_jobs=-1,
        random_state=42,
        verbosity=0 # Silence output during tuning
    )

    # Fit XG boost reranker
    XGB_model.fit(
        X_train,
        y_train,
        group=groups,
        verbose=True
    )

    # Evaluate training performance
    y_pred_scores = XGB_model.predict(X_train)
    auc_score = roc_auc_score(y_train, y_pred_scores)
    print(f"Training AUC Score: {auc_score:.4f}")

    # Set the XGB model in the recommender
    recommender.XGB_model = XGB_model
    
    # Evaluate
    score = evaluate_recommender(recommender, at=20, URM_validation=URM_outer)
    print(f"Validation Score (RECALL@20): {score:.4f}")

    optimizer.log_folds([score], params)

    return score

In [12]:
optuna_study = optimizer.create_and_optimize_study(
    study_name=STUDY_NAME,
    objective_function=objective_function,
    n_trials=100
)

[I 2025-11-27 20:31:54,669] A new study created in RDB with name: XGBoostRerankerRecommender_v1_1

  0%|          | 0/100 [00:00<?, ?it/s]

Training AUC Score: 0.7894
[W 2025-11-27 20:49:29,179] Trial 0 failed with parameters: {'learning_rate': 0.01222982191393915, 'n_estimators': 567, 'max_depth': 3, 'reg_alpha': 0.7709208908307081, 'reg_lambda': 0.41703497767977304, 'colsample_bytree': 0.7895213800179919, 'subsample': 0.9730498550868242, 'objective': 'rank:ndcg'} because of the following error: UnboundLocalError("cannot access local variable 'df' where it is not associated with a value").
Traceback (most recent call last):
  File "/home/luigi/.venvs/recsys/lib/python3.13/site-packages/optuna/study/_optimize.py", line 201, in _run_trial
    value_or_values = func(trial)
  File "/tmp/ipykernel_30608/342212902.py", line 50, in objective_function
    if df is None or index_df is None or user_map is None:
       ^^
UnboundLocalError: cannot access local variable 'df' where it is not associated with a value
[W 2025-11-27 20:49:29,195] Trial 0 failed with value None.

UnboundLocalError: cannot access local variable 'df' where it is not associated with a value

In [ ]:
optuna.visualization.plot_optimization_history(optuna_study)

In [ ]:
optuna.visualization.plot_param_importances(optuna_study)

In [ ]:
optuna.visualization.plot_parallel_coordinate(optuna_study)

## **Change ranges of Optimization**

In [ ]:
STUDY_NAME = XGBoostRerankerRecommender.RECOMMENDER_NAME + "_v1_2"

In [ ]:
def objective_function(optuna_trial: optuna.trial.Trial) -> float:    
    params = {
        'learning_rate': optuna_trial.suggest_float('learning_rate', 1e-3, 0.2, log=True),
        'n_estimators': optuna_trial.suggest_int('n_estimators', 20, 1000),
        'max_depth': optuna_trial.suggest_int('max_depth', 4, 14),
        'reg_alpha': optuna_trial.suggest_float('reg_alpha', 1e-3, 100.0, log=True),
        'reg_lambda': optuna_trial.suggest_float('reg_lambda', 1e-4, 10.0, log=True),
        'colsample_bytree': optuna_trial.suggest_float('colsample_bytree', 0.4, 0.9),
        'subsample': optuna_trial.suggest_float('subsample', 0.6, 1.0),
        
        'objective': 'rank:ndcg',
        'grow_policy': 'depthwise'
    }

    # Instantiate XGB model with current hyperparameters
    XGB_model = XGBRanker(
        objective=params['objective'],
        n_estimators=params['n_estimators'],
        learning_rate=params['learning_rate'],
        max_depth=params['max_depth'],
        reg_alpha=params['reg_alpha'],
        reg_lambda=params['reg_lambda'],
        colsample_bytree=params['colsample_bytree'],
        subsample=params['subsample'],
        grow_policy=params['grow_policy'],
        n_jobs=-1,
        random_state=42,
        verbosity=0
    )

    # Fit XG boost reranker
    XGB_model.fit(
        X_train,
        y_train,
        group=groups,
        verbose=True
    )

    # Evaluate training performance
    y_pred_scores = XGB_model.predict(X_train)
    auc_score = roc_auc_score(y_train, y_pred_scores)
    print(f"Training AUC Score: {auc_score:.4f}")

    # Instantiate the recommender with the trained XGB model
    recommender_instance = XGBoostRerankerRecommender(
        XGB_model=XGB_model,
        df=X_val
    )
    
    # Evaluate
    score = evaluate_recommender(recommender_instance, at=20, URM_validation=URM_val)
    print(f"Validation Score (RECALL@20): {score:.4f}")

    optimizer.log_folds([score], params)

    return score

In [ ]:
optuna_study = optimizer.create_study(STUDY_NAME, pruner=None)

In [ ]:
known_best_params = {
    'learning_rate': 0.0333,
    'n_estimators': 456, 
    'max_depth': 10,
    'reg_alpha': 9.81,
    'reg_lambda': 0.006,
    'colsample_bytree': 0.59,
    'subsample': 0.82
}

# Enqueue the known best parameters as a trial
optuna_study.enqueue_trial(known_best_params)

In [ ]:
optimizer.optimize(
    objective_function=objective_function,
    n_trials=100
)

In [ ]:
optuna.visualization.plot_optimization_history(optuna_study)

In [ ]:
optuna.visualization.plot_param_importances(optuna_study)

In [ ]:
optuna.visualization.plot_parallel_coordinate(optuna_study)