In [1]:
from getpass import getpass
import sys, os

REPO_NAME = "RecSys-Challenge-2025"
REPO_URL  = f"github.com/Lv1g1/{REPO_NAME}.git"
LOCAL_REPO_PATH = f"/content/{REPO_NAME}"

# Mount Google Drive first (Colab only)
if '/content' in os.getcwd():
    from google.colab import drive
    drive.mount('/content/drive', force_remount=False)

# Clone only if not existing
if not os.path.exists(LOCAL_REPO_PATH):
    print("Cloning repo...")
    token = getpass("GitHub Token: ")
    !git clone https://{token}@{REPO_URL}
else:
    print("Repo already exists — pulling latest changes")
    os.chdir(LOCAL_REPO_PATH)
    !git pull
    os.chdir("/content")

# Enable import of your modules
if LOCAL_REPO_PATH not in sys.path:
    os.chdir(LOCAL_REPO_PATH)
    sys.path.append(os.getcwd())
    os.chdir("/content")

Mounted at /content/drive
Cloning repo...
GitHub Token: ··········
Cloning into 'RecSys-Challenge-2025'...
remote: Enumerating objects: 210, done.
remote: Counting objects: 100% (210/210), done.
remote: Compressing objects: 100% (160/160), done.
remote: Total 210 (delta 55), reused 197 (delta 44), pack-reused 0 (from 0)
Receiving objects: 100% (210/210), 7.33 MiB | 4.85 MiB/s, done.
Resolving deltas: 100% (55/55), done.

In [2]:
import importlib
import numpy as np
import scipy.sparse as sps

from Challenge import paths
importlib.reload(paths)

Running on: colab — BASE_DIR = /content/drive/MyDrive/RecSys/demo
Running on: colab — BASE_DIR = /content/drive/MyDrive/RecSys/demo

In [3]:
# Load datasets
URM_train = sps.load_npz(paths.URM_TRAIN)
URM_validation = sps.load_npz(paths.URM_VALIDATION)

In [21]:
from Evaluation.Evaluator import EvaluatorHoldout

evaluator = EvaluatorHoldout(URM_validation, cutoff_list=[10])

EvaluatorHoldout: Ignoring 76 ( 0.1%) Users that have less than 1 test interactions

In [22]:
from Recommenders.NonPersonalizedRecommender import TopPop

recTopPop = TopPop(URM_train)
recTopPop.fit()

result_df, _ = evaluator.evaluateRecommender(recTopPop)
result_df['MAP']

TopPopRecommender: URM Detected 25 ( 0.2%) items with no interactions.
EvaluatorHoldout: Processed 69802 (100.0%) in 44.40 sec. Users per second: 1572

cutoff
10    0.103854
Name: MAP, dtype: object

In [16]:
from Recommenders.NonPersonalizedRecommender import Random

recRandom = Random(URM_train)
recRandom.fit()

result_df, _ = evaluator.evaluateRecommender(recRandom)
result_df['MAP']

RandomRecommender: URM Detected 25 ( 0.2%) items with no interactions.
EvaluatorHoldout: Processed 69802 (100.0%) in 54.51 sec. Users per second: 1281

cutoff
10    0.000802
Name: MAP, dtype: object

In [17]:
from Recommenders.NonPersonalizedRecommender import GlobalEffects

recGlobalEffects = GlobalEffects(URM_train)
recGlobalEffects.fit()

result_df, _ = evaluator.evaluateRecommender(recGlobalEffects)
result_df['MAP']

GlobalEffectsRecommender: URM Detected 25 ( 0.2%) items with no interactions.
EvaluatorHoldout: Processed 69802 (100.0%) in 41.77 sec. Users per second: 1671

cutoff
10    0.030854
Name: MAP, dtype: object

In [18]:
recTopPop.save_model(paths.MODEL_DIR)
recRandom.save_model(paths.MODEL_DIR)
recGlobalEffects.save_model(paths.MODEL_DIR)

TopPopRecommender: Saving model in file '/content/drive/MyDrive/RecSys/demo/modelsTopPopRecommender'
TopPopRecommender: Saving complete
RandomRecommender: Saving model in file '/content/drive/MyDrive/RecSys/demo/modelsRandomRecommender'
RandomRecommender: Saving complete
GlobalEffectsRecommender: Saving model in file '/content/drive/MyDrive/RecSys/demo/modelsGlobalEffectsRecommender'
GlobalEffectsRecommender: Saving complete